### ISSUE TITLE
Cannot sort any inventory

### ISSUE THREAD

**Issue by NewbieOrange** [NewbieOrange/clicksort#20]
Seems to be related to this change: https://github.com/NewbieOrange/clicksort/commit/ac50df8e153de29ba678074272d12bb46d387165#diff-2773bcd54566eabeb583594a8820ea67622db41bdfedf1d2c346eae6c6b02ba4R417

Log when sorting a full player inventory below. It attempts to put all items into the hotbar, which I thought should not happen. 1 Item also landed in the offhand slot. See attached picture.

```
[18:15:13 INFO]: [ClickSort] Permission check: player=minoneer, node=clicksort.sort, allowed=true
[18:15:13 INFO]: [ClickSort] inventory click by player minoneer: type=SWAP_OFFHAND slot=21 rawslot=21
[18:15:13 INFO]: [ClickSort] clicked inventory window PLAYER, slot 21
[18:15:13 INFO]: [ClickSort] Permission check: player=minoneer, node=clicksort.sort.player, allowed=true
[18:15:13 INFO]: [ClickSort] sortAndMerge: sortable = [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], size = 41
[18:15:13 INFO]: [ClickSort] Process item [SortKey[BEACON|BEACON|0|meta-type=TILE_ENTITY;blockMaterial=BEACON;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for BEACON = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[BLACK_CARPET|BLACK_CARPET|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for BLACK_CARPET = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[CALIBRATED_SCULK_SENSOR|CALIBRATED_SCULK_SENSOR|0|meta-type=TILE_ENTITY;blockMaterial=CALIBRATED_SCULK_SENSOR;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for CALIBRATED_SCULK_SENSOR = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[CHAIN|CHAIN|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for CHAIN = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[CHAINMAIL_BOOTS|CHAINMAIL_BOOTS|0|meta-type=ARMOR;]], amount = 1
[18:15:13 INFO]: [ClickSort] max stack size for CHAINMAIL_BOOTS = 1
[18:15:13 INFO]: [ClickSort] Process item [SortKey[CHEST|CHEST|0|meta-type=TILE_ENTITY;blockMaterial=CHEST;]], amount = 47
[18:15:13 INFO]: [ClickSort] max stack size for CHEST = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[CRYING_OBSIDIAN|CRYING_OBSIDIAN|0|meta-type=UNSPECIFIC;]], amount = 32
[18:15:13 INFO]: [ClickSort] max stack size for CRYING_OBSIDIAN = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[DIRT|DIRT|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for DIRT = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[DIRT_PATH|DIRT_PATH|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for DIRT_PATH = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[DRIPSTONE_BLOCK|DRIPSTONE_BLOCK|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for DRIPSTONE_BLOCK = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[GOLDEN_CARROT|GOLDEN_CARROT|0|meta-type=UNSPECIFIC;]], amount = 1
[18:15:13 INFO]: [ClickSort] max stack size for GOLDEN_CARROT = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[GRAY_WOOL|GRAY_WOOL|0|meta-type=UNSPECIFIC;]], amount = 128
[18:15:13 INFO]: [ClickSort] max stack size for GRAY_WOOL = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[MAGMA_BLOCK|MAGMA_BLOCK|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for MAGMA_BLOCK = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[MOSS_CARPET|MOSS_CARPET|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for MOSS_CARPET = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[MULE_SPAWN_EGG|MULE_SPAWN_EGG|0|meta-type=SPAWN_EGG;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for MULE_SPAWN_EGG = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[OAK_BUTTON|OAK_BUTTON|0|meta-type=UNSPECIFIC;]], amount = 1
[18:15:13 INFO]: [ClickSort] max stack size for OAK_BUTTON = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[OAK_WOOD|OAK_WOOD|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for OAK_WOOD = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[PEARLESCENT_FROGLIGHT|PEARLESCENT_FROGLIGHT|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for PEARLESCENT_FROGLIGHT = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[RED_CARPET|RED_CARPET|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for RED_CARPET = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[RED_SANDSTONE|RED_SANDSTONE|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for RED_SANDSTONE = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[SADDLE|SADDLE|0|meta-type=UNSPECIFIC;]], amount = 1
[18:15:13 INFO]: [ClickSort] max stack size for SADDLE = 1
[18:15:13 INFO]: [ClickSort] Process item [SortKey[SANDSTONE|SANDSTONE|0|meta-type=UNSPECIFIC;]], amount = 128
[18:15:13 INFO]: [ClickSort] max stack size for SANDSTONE = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[SCULK_SHRIEKER|SCULK_SHRIEKER|0|meta-type=TILE_ENTITY;blockMaterial=SCULK_SHRIEKER;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for SCULK_SHRIEKER = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[TARGET|TARGET|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for TARGET = 64
[18:15:13 INFO]: [ClickSort] Process item [SortKey[WHITE_WOOL|WHITE_WOOL|0|meta-type=UNSPECIFIC;]], amount = 64
[18:15:13 INFO]: [ClickSort] max stack size for WHITE_WOOL = 64
[18:15:13 INFO]: [ClickSort] dropping ItemStack{PEARLESCENT_FROGLIGHT x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{RED_CARPET x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{RED_SANDSTONE x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{SADDLE x 1} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{SANDSTONE x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{SANDSTONE x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{SCULK_SHRIEKER x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{TARGET x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping ItemStack{WHITE_WOOL x 64} by player minoneer
[18:15:13 INFO]: [ClickSort] dropping null by player minoneer
[18:15:13 ERROR]: Could not pass event InventoryClickEvent to ClickSort v1.6.1
java.lang.IllegalArgumentException: ItemStack cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftWorld.dropItemNaturally(CraftWorld.java:764) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.CraftWorld.dropItemNaturally(CraftWorld.java:758) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at ClickSort.jar/me.desht.clicksort.ClickSortPlugin.sortInventory(ClickSortPlugin.java:365) ~[ClickSort.jar:?]
        at ClickSort.jar/me.desht.clicksort.ClickSortPlugin.onInventoryClicked(ClickSortPlugin.java:213) ~[ClickSort.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor517.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-137-bd5867a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3177) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

<img width="963" alt="image" src="https://github.com/NewbieOrange/clicksort/assets/6442649/e1d887c9-2412-4807-9b74-1f7c302f8c7a">

_Originally posted by @minoneer in https://github.com/NewbieOrange/clicksort/issues/19#issuecomment-2166146842_

**Comment by minoneer** [comment]
Lol, seems like we had the same idea at the same time - #21

**Comment by NewbieOrange** [comment]
Close this as duplicate. Continue on #21
